/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface EduVaultMarketplaceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "buyPrompt"
      | "getPrompt"
      | "hasLicense"
      | "listPrompt"
      | "proceedsOf"
      | "withdrawProceeds"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "PromptListed" | "PromptPurchased" | "Withdrawn"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "buyPrompt",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPrompt",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasLicense",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "listPrompt",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "proceedsOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawProceeds",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "buyPrompt", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getPrompt", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasLicense", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "listPrompt", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "proceedsOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawProceeds",
    data: BytesLike
  ): Result;
}

export namespace PromptListedEvent {
  export type InputTuple = [
    promptId: BigNumberish,
    seller: AddressLike,
    priceWei: BigNumberish,
    metadataURI: string
  ];
  export type OutputTuple = [
    promptId: bigint,
    seller: string,
    priceWei: bigint,
    metadataURI: string
  ];
  export interface OutputObject {
    promptId: bigint;
    seller: string;
    priceWei: bigint;
    metadataURI: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PromptPurchasedEvent {
  export type InputTuple = [
    promptId: BigNumberish,
    buyer: AddressLike,
    priceWei: BigNumberish
  ];
  export type OutputTuple = [promptId: bigint, buyer: string, priceWei: bigint];
  export interface OutputObject {
    promptId: bigint;
    buyer: string;
    priceWei: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawnEvent {
  export type InputTuple = [seller: AddressLike, amount: BigNumberish];
  export type OutputTuple = [seller: string, amount: bigint];
  export interface OutputObject {
    seller: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EduVaultMarketplace extends BaseContract {
  connect(runner?: ContractRunner | null): EduVaultMarketplace;
  waitForDeployment(): Promise<this>;

  interface: EduVaultMarketplaceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  buyPrompt: TypedContractMethod<[promptId: BigNumberish], [void], "payable">;

  getPrompt: TypedContractMethod<
    [promptId: BigNumberish],
    [
      [string, bigint, string, boolean] & {
        seller: string;
        priceWei: bigint;
        metadataURI: string;
        isActive: boolean;
      }
    ],
    "view"
  >;

  hasLicense: TypedContractMethod<
    [promptId: BigNumberish, user: AddressLike],
    [boolean],
    "view"
  >;

  listPrompt: TypedContractMethod<
    [metadataURI: string, priceWei: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  proceedsOf: TypedContractMethod<[seller: AddressLike], [bigint], "view">;

  withdrawProceeds: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "buyPrompt"
  ): TypedContractMethod<[promptId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "getPrompt"
  ): TypedContractMethod<
    [promptId: BigNumberish],
    [
      [string, bigint, string, boolean] & {
        seller: string;
        priceWei: bigint;
        metadataURI: string;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasLicense"
  ): TypedContractMethod<
    [promptId: BigNumberish, user: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "listPrompt"
  ): TypedContractMethod<
    [metadataURI: string, priceWei: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "proceedsOf"
  ): TypedContractMethod<[seller: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "withdrawProceeds"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "PromptListed"
  ): TypedContractEvent<
    PromptListedEvent.InputTuple,
    PromptListedEvent.OutputTuple,
    PromptListedEvent.OutputObject
  >;
  getEvent(
    key: "PromptPurchased"
  ): TypedContractEvent<
    PromptPurchasedEvent.InputTuple,
    PromptPurchasedEvent.OutputTuple,
    PromptPurchasedEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawn"
  ): TypedContractEvent<
    WithdrawnEvent.InputTuple,
    WithdrawnEvent.OutputTuple,
    WithdrawnEvent.OutputObject
  >;

  filters: {
    "PromptListed(uint256,address,uint256,string)": TypedContractEvent<
      PromptListedEvent.InputTuple,
      PromptListedEvent.OutputTuple,
      PromptListedEvent.OutputObject
    >;
    PromptListed: TypedContractEvent<
      PromptListedEvent.InputTuple,
      PromptListedEvent.OutputTuple,
      PromptListedEvent.OutputObject
    >;

    "PromptPurchased(uint256,address,uint256)": TypedContractEvent<
      PromptPurchasedEvent.InputTuple,
      PromptPurchasedEvent.OutputTuple,
      PromptPurchasedEvent.OutputObject
    >;
    PromptPurchased: TypedContractEvent<
      PromptPurchasedEvent.InputTuple,
      PromptPurchasedEvent.OutputTuple,
      PromptPurchasedEvent.OutputObject
    >;

    "Withdrawn(address,uint256)": TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
    Withdrawn: TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
  };
}
